{% set name = "texplain" %}
{% set org = "tdegeus" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3e91b6cb0bd38a1e34d555f6553d5c6f29edfda55d65ac451ad4891c114a2375

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - texplain = {{ name }}:_texplain_cli
    - texcleanup = {{ name }}:_texcleanup_cli
    - texindent = {{ name }}:_texindent_cli

requirements:
  host:
    - pip
    - python >=3
    - setuptools_scm
  run:
    - click
    - numpy
    - python >=3
    - typing_extensions

test:
  requires:
    - pip
  imports:
    - {{ name }}
  commands:
    - pip check
    - python -c "import {{ name }}; assert {{ name }}.version == '{{ version }}'"
    - texplain --version | grep {{ version }}
    - texcleanup --version | grep {{ version }}
    - texindent --version | grep {{ version }}

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Formatting tools for TeX files
  description: Formatting tools for TeX files
  doc_url: https://github.com/{{ org }}/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
