{% set name = "texplain" %}
{% set version = "0.3.3" %}
{% set sha256 = "eacacb88c0da598286fb14e5a8410b14d5da9cc510732a8228dccddb432e8fc7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/texplain/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - texplain = texplain:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - docopt
    - click
    - numpy

test:
  imports:
    - texplain
  commands:
    - texplain --help

about:
  home: https://github.com/tdegeus/texplain
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Create a directory with a TeX-file and only its dependencies'
  description: 'Create a directory with a TeX-file and only its dependencies'
  doc_url: https://github.com/tdegeus/texplain
  dev_url: https://github.com/tdegeus/texplain

extra:
  recipe-maintainers:
    - tdegeus
