{% set name = "texplain" %}
{% set org = "tdegeus" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7364acdf533bb61833a54ee10330373982c57f7fce441b62dc136c016bd17111

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - texplain = texplain:_texplain_catch
    - texcleanup = texplain:_texcleanup_catch

requirements:
  host:
    - pip
    - python >=3
    - setuptools_scm
  run:
    - click
    - numpy
    - python >=3

test:
  imports:
    - {{ name }}
  commands:
    - pip check
    - python -c "import {{ name }}; print({{ name }}.version)"
    - texplain --version
    - texcleanup --version
  requires:
    - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Clean-up TeX files and/or create clean output directory
  description: Clean-up TeX files and/or create clean output directory
  doc_url: https://github.com/{{ org }}/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
